### ISSUE TITLE
Google Sheets belgesi ile senkronize çokdilli terimce uygulaması

### ISSUE THREAD

**Issue by abdullahsadikkuralay** [hakandilek/afet-tercume#1]
Çevirmenlerin çevrimdışı kullanabileceği, az şarj harcayan, yeni terimler eklendikçe bilgileri Google Sheets'ten çekecek ve kullanıcı dostu arama özellikleri olan bir iOS ve Android uygulaması ihtiyacımız var.

Terimce linki: https://docs.google.com/spreadsheets/d/1LfFJZxpbCbz2lRpKQ0_kTMKNJVDJ9FyrlAoP15TU8wU/edit?usp=sharing

**Comment by hakandilek** [comment]
@abdullahsadikkuralay kapatalim mi bunu?

**Comment by abdullahsadikkuralay** [comment]
@hakandilek Evet kapatabiliriz.
