### ISSUE TITLE
satıra sığmayan ifadeler

### ISSUE THREAD

**Issue by AhmetErgn6** [hakandilek/afet-tercume#28]
Satıra sığmayacak kadar uzun olan ifade alt satıra geçmiyor, direkt kesiliyor.
Örnek: "Sağ/sol elinin/ayağının parmaklarını hareket ettirebiliyor musun?" ifadesi "Sağ/sol elinin/ayağının parmaklarını hareke" şeklinde gözüküyor.

**Comment by aliilkertopcu** [comment]
This bug has been solved already.
![image](https://user-images.githubusercontent.com/5613150/221869628-29066323-d397-4a16-aa6c-7c50750cf680.png)
